# Site settings
author: benevolent-demo-1612
title: 
header-img: img/home-bg.png
email: tevinsherman@yahoo.com
copyright_name: benevolent-demo-1612
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TevinFinessin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
